variables:
  COMPOSE_ISOLATION: "buildpipeline${CI_PIPELINE_ID}"

before_script:
  - export COMPOSE_PROJECT_NAME=${COMPOSE_ISOLATION}${CI_BUILD_NAME}
  - export COMPOSE_NETWORK_TUPLE_C=$(expr ${CI_BUILD_ID} % 99)
  - cd tests

after_script:
  - export COMPOSE_PROJECT_NAME=${COMPOSE_ISOLATION}${CI_BUILD_NAME}
  - cd tests
  - docker-compose down -v

.build: &build
  stage: build
  script:
    - sh run.sh

php-5.6-apache:
  variables:
    VARIANT: "apache"
    VERSION: "5.6"
  <<: *build

php-5.6-fpm:
  variables:
    VARIANT: "fpm"
    VERSION: "5.6"
  <<: *build

php-5.6-fpm-alpine:
  variables:
    VARIANT: "fpm-alpine"
    VERSION: "5.6"
  <<: *build

php-7.0-apache:
  variables:
    VARIANT: "apache"
    VERSION: "7.0"
  <<: *build

php-7.0-fpm:
  variables:
    VARIANT: "fpm"
    VERSION: "7.0"
  <<: *build

php-7.0-fpm-alpine:
  variables:
    VARIANT: "fpm-alpine"
    VERSION: "7.0"
  <<: *build

php-7.1-apache:
  variables:
    VARIANT: "apache"
    VERSION: "7.1"
  <<: *build

php-7.1-fpm:
  variables:
    VARIANT: "fpm"
    VERSION: "7.1"
  <<: *build

php-7.1-fpm-alpine:
  variables:
    VARIANT: "fpm-alpine"
    VERSION: "7.1"
  <<: *build
