variables:
  ISOLATION: "buildpipeline${CI_PIPELINE_ID}"

before_script:
  - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}

after_script:
  - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}
  - docker-compose down -v

php-5.6-apache:
  stage: build
  script:
    - docker-compose build --pull ${CI_BUILD_NAME}

php-5.6-fpm:
  stage: build
  script:
    - docker-compose build --pull ${CI_BUILD_NAME}

php-7.0-apache:
  stage: build
  script:
    - docker-compose build --pull ${CI_BUILD_NAME}

php-7.0-fpm:
  stage: build
  script:
    - docker-compose build --pull ${CI_BUILD_NAME}

php-7.1-apache:
  stage: build
  script:
    - docker-compose build --pull ${CI_BUILD_NAME}

php-7.1-fpm:
  stage: build
  script:
    - docker-compose build --pull ${CI_BUILD_NAME}