variables:
  ISOLATION: "buildpipeline${CI_PIPELINE_ID}"

before_script:
  - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}

after_script:
  - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}
  - docker-compose down -v

.build: &build
  stage: build
  script:
    - docker-compose build --pull ${CI_BUILD_NAME}
    - docker-compose run --rm ${CI_BUILD_NAME} php /tests/requirements.php

php-5.6-apache:
  <<: *build

php-5.6-fpm:
  <<: *build

php-7.0-apache:
  <<: *build

php-7.0-fpm:
  <<: *build

php-7.1-apache:
  <<: *build

php-7.1-fpm:
  <<: *build
